<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.dbeaver.common</groupId>
        <artifactId>com.dbeaver.common.main</artifactId>
        <version>2.2.0-SNAPSHOT</version>
        <relativePath>../</relativePath>
    </parent>
    <artifactId>com.dbeaver.common.modules</artifactId>
    <name>Common modules</name>
    <packaging>pom</packaging>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>Serge Rider</name>
            <email>serge@dbeaver.com</email>
            <url>https://github.com/serge-rider</url>
            <organization>DBeaver Corp</organization>
            <organizationUrl>https://github.com/dbeaver</organizationUrl>
        </developer>
    </developers>

    <issueManagement>
        <system>github</system>
        <url>https://github.com/dbeaver/dbeaver/issues</url>
    </issueManagement>

    <scm>
        <connection>scm:git:git@github.com:dbeaver/dbeaver-common.git</connection>
        <developerConnection>scm:git:git@github.com:dbeaver/dbeaver-common.git</developerConnection>
        <url>git@github.com:dbeaver/dbeaver-common.git</url>
    </scm>

    <properties>
        <sonar.organization>teamlead</sonar.organization>
        <sonar.host.url>https://sonarcloud.io</sonar.host.url>
        <sonar.projectKey>teamlead_java-maven-sonatype-starter</sonar.projectKey>
    </properties>

    <modules>
        <module>org.jkiss.utils</module>
        <module>com.dbeaver.jdbc.api</module>
        <module>com.dbeaver.rpc</module>
    </modules>

    <profiles>
        <profile>
            <!-- Sonatype deploy -->
            <id>sonatypeDeploy</id>
            <build>
                <plugins>
                    <!--<plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>0.3.0</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>central</publishingServerId>
                            <tokenAuth>true</tokenAuth>
                            <autoPublish>true</autoPublish>
                            <waitUntil>published</waitUntil>
                        </configuration>
                    </plugin>-->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                                <configuration>
                                    <gpgArguments>
                                        <arg>--pinentry-mode</arg>
                                        <arg>loopback</arg>
                                    </gpgArguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
