name: Build

on:
  workflow_call:
    outputs:
      run-id:
        value: ${{ jobs.build-and-test.outputs.run-id }}

jobs:
  build-and-test:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    outputs:
      run-id: ${{ github.run_id }}

    steps:
      - name: Checkout dbeaver-vscode
        uses: actions/checkout@v4

      - uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Build
        run: mvn -B -T 1C clean package

