name: Lint

on:
  # Allows you to reuse workflows by referencing their YAML files
  workflow_call:

concurrency:
  group: |
      # For pull requests, group by the pull request ID
      ${{ github.event_name == 'pull_request' && format('pr-{0}-java-checkstyle', github.event.pull_request.number) }}

      # For pushes to main, group by the branch name (e.g., 'main')
      ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'main-branch-java-checkstyle' }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Checkout checkstyle config repository
        uses: actions/checkout@v4
        with:
          repository: dbeaver/dbeaver
          path: dbeaver-config

      - name: Copy checkstyle config
        run: cp dbeaver-config/dbeaver-checkstyle-config.xml ./dbeaver-checkstyle-config.xml

      - name: Remove checkstyle config directory
        run: rm -rf dbeaver-config

      - uses: dbeaver/github-actions/install-maven@devel

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - uses: Wroud/github-actions/java-checkstyle@78998f6de835e929c0bcb5fbe2eefeb0899d0c0c
        with:
          checkstyle_config: ./dbeaver-checkstyle-config.xml

      # - uses: dbelyaev/action-checkstyle@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     reporter: github-pr-annotations
      #     filter_mode: diff_context
      #     checkstyle_config: ./dbeaver-checkstyle-config.xml
      #     fail_on_error: true
