name: MVN Package

on:
  workflow_call:
    inputs:
      project-directory:
        required: false
        type: string
      timeout-minutes:
        required: false
        type: number
        default: 10
      project-deps:
        required: false
        type: string
      mvn-args:
        required: false
        type: string

    outputs:
      run-id:
        value: ${{ jobs.build-and-test.outputs.run-id }}

    secrets:
      DEVOPS_ISSUE_RO_TOKEN: 
        required: false

concurrency:
  group: ${{ github.event_name == 'pull_request' && format('pr-{0}-mvn-package', github.event.pull_request.number) || 'mvn-package' }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    permissions:
      contents: read

    outputs:
      run-id: ${{ github.run_id }}

    steps:
      - name: Set repository path variable
        run: echo "CHECKOUT_PATH=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          path: ${{ env.CHECKOUT_PATH || '.' }}

      - uses: dbeaver/github-actions/clone-repositories@devel
        if: ${{ inputs.project-deps != null }}
        with:
          project_deps_path: ${{ inputs.project-deps }}
          token: ${{ secrets.DEVOPS_ISSUE_RO_TOKEN }}

      - uses: dbeaver/github-actions/install-maven@devel
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Build
        run: mvn clean package -B -T 1C ${{ inputs.mvn-args }}
        working-directory: ${{ inputs.project-directory || env.CHECKOUT_PATH || '.' }}

