name: MVN Package

on:
  workflow_call:
    inputs:
      project-directory:
        required: false
        type: string
      timeout-minutes:
        required: false
        type: number
        default: 10
      project-deps:
        required: false
        type: string
      mvn-args:
        required: false
        type: string
      cache-target:
        required: false
        type: string
      clean:
        required: false
        type: boolean

    outputs:
      run-id:
        value: ${{ jobs.build-and-test.outputs.run-id }}

    secrets:
      DEVOPS_ISSUE_RO_TOKEN: 
        required: false

concurrency:
  group: ${{ github.event_name == 'pull_request' && format('pr-{0}-mvn-package', github.event.pull_request.number) || 'mvn-package' }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    permissions:
      contents: read

    outputs:
      run-id: ${{ github.run_id }}

    steps:
      - name: Set repository path variable
        run: echo "CHECKOUT_PATH=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          path: ${{ env.CHECKOUT_PATH || '.' }}

      - uses: dbeaver/github-actions/clone-repositories@a9c8157cf1f0370b8c044c2e271c1d5f7104c836
        id: clone-repositories
        if: ${{ inputs.project-deps != null }}
        with:
          project_deps_path: ${{ inputs.project-deps }}
          token: ${{ secrets.DEVOPS_ISSUE_RO_TOKEN }}

      - name: Setup caching paths
        id: cache-paths
        run: |
          CACHE_PATHS="${{ env.CHECKOUT_PATH || '.' }}/**/target/ "
          for repo in ${{ steps.clone-repositories.outputs.cloned-folders }}; do
            CACHE_PATHS+="$repo/**/target/ "
          done
          if [[ -n "${{ inputs.cache-target }}" ]]; then
            CACHE_PATHS+="${{ inputs.cache-target }}"
          fi
          echo "CACHE_PATHS=$CACHE_PATHS" >> $GITHUB_ENV

      - name: Cache target folders
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_PATHS }}
          key: mvn-build-cache-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            mvn-build-cache-${{ runner.os }}-
            mvn-build-cache-

      - uses: dbeaver/github-actions/install-maven@devel
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven
      
      - name: Clean
        if: ${{ inputs.clean == true }}
        run: mvn clean -B
        working-directory: ${{ inputs.project-directory || env.CHECKOUT_PATH || '.' }}

      - name: Build
        run: mvn package -B -T 1C ${{ inputs.mvn-args }}
        working-directory: ${{ inputs.project-directory || env.CHECKOUT_PATH || '.' }}
