name: Maven Verify

on:
  workflow_call:
    inputs:
      project-directory:
        required: false
        type: string
      timeout-minutes:
        required: false
        type: number
        default: 10
      project-deps:
        required: false
        type: string
      mvn-args:
        required: false
        type: string
      use-public-p2:
        type: boolean
        default: true
      use-private-p2:
        type: boolean
        default: false

    outputs:
      run-id:
        value: ${{ jobs.build-and-test.outputs.run-id }}

    secrets:
      DEVOPS_ISSUE_RO_TOKEN:
        required: false

jobs:
  build-and-test:
    name: Build Java
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    permissions:
      contents: read

    outputs:
      run-id: ${{ github.run_id }}

    env:
      MAVEN_OPTS: -Xmx2048m

    steps:
      - uses: dbeaver/github-actions/prepare-for-a-maven-lifecycle@devel
        with:
          project-deps: ${{ inputs.project-deps }}
          token: ${{ secrets.DEVOPS_ISSUE_RO_TOKEN }}

      - name: Prepare custom p2
        id: prepare-custom-p2
        shell: bash
        if: ${{ github.event_name == 'pull_request' && inputs.p2-repos-to-mvn-flags-map != '' }}
        env:
          GH_TOKEN: ${{ secrets.DEVOPS_ISSUE_RO_TOKEN }}
        run: |
          declare -A p2_map
          if [ ${{ inputs.use-public-p2 }} = 'true' ]; then
            p2_map['dbeaver-deps-ce']='repo.p2.dbeaver-ce.url'
          fi
          if [ ${{ inputs.use-private-p2 }} = 'true' ]; then
            p2_map['dbeaver-deps-pro']='repo.p2.dbeaver-pro.url'
          fi
          if [ -n "$GH_TOKEN" ]; then
              gh_auth_header="-H \"Authorization: token $GH_TOKEN\""
          fi
          uri_encoded_branch_name=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$GITHUB_HEAD_REF")
          output=''
          for repo in ${!p2_map[@]}
          do
              flag="${p2_map[${repo}]}"
              echo "repo: $repo, flag: $flag"
              # Check if exists a branch with the same name in $repo
              http_status=$(curl -s -o /dev/null -w "%{http_code}" "$gh_auth_header" \
                  -H "Accept: application/vnd.github.v3+json" \
                  "https://api.github.com/repos/$GITHUB_REPOSITORY_OWNER/$repo/branches/$uri_encoded_branch_name")
              if [ "$http_status" != '200' ]; then
                  echo "Status $http_status: Branch $GITHUB_HEAD_REF does not exist in $GITHUB_REPOSITORY_OWNER/$repo."
                  continue
              fi
              git clone --depth 1 -b "$GITHUB_HEAD_REF" "https://$GH_TOKEN@github.com/$GITHUB_REPOSITORY_OWNER/$repo.git"
              while IFS= read -r dep_repo; do
                  if [ -d "$dep_repo" ]; then
                      echo "Not cloning $dep_repo since a folder with such a name already exists. Most likely, another step already cloned this repo."
                      continue
                  fi
                  default_branch=$(git ls-remote --symref "https://$GH_TOKEN@github.com/dbeaver/$dep_repo.git" HEAD | grep '^ref:' | awk '{print $2}' | sed 's|refs/heads/||')
                  git clone --depth 1 -b "$GITHUB_HEAD_REF" "https://$GH_TOKEN@github.com/$GITHUB_REPOSITORY_OWNER/$dep_repo.git" || \
                  git clone --depth 1 -b "$default_branch" "https://$GH_TOKEN@github.com/dbeaver/$dep_repo.git"
              done < "$repo/project.deps"
              mvn clean verify -B -T1C -f "$repo"
              mvn clean verify -B -T1C -f "$repo/p2"
              if [ -n "$output" ]; then
                  output+=" "
              fi
              p2_uri="file://$(realpath ./$repo/p2/repository/target/repository)"
              output+="-D$flag='$p2_uri'"
          done
          if [ -n "$output" ]; then
            echo "p2-mvn-flags=$output" >> "$GITHUB_OUTPUT"
          fi

      - name: Compile
        run: mvn clean verify -B -T1C ${{ inputs.mvn-args }} ${{ steps.prepare-custom-p2.outputs.p2-mvn-flags }}
        working-directory: ${{ inputs.project-directory || env.CHECKOUT_PATH || '.' }}
