name: Cleanup

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - devel

jobs:
  delete-caches:
    name: Cleanup
    uses: ./.github/workflows/cleanup-caches.yml
    secrets: inherit
