name: CI

on:
  workflow_call:
    inputs:
      mvn-clean:
        required: false
        type: boolean
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches: [devel]

jobs:
  build:
    uses: ./.github/workflows/mvn-package.yml
    name: Check
    secrets: inherit
    with:
      timeout-minutes: 5
      clean: ${{ inputs.mvn-clean || false }}

  lint:
    uses: ./.github/workflows/java-checkstyle.yml
    name: Check
    secrets: inherit
